In [6]:
import numpy as np
array = np.array([8, 10, 2, 9, 7, 5])
target = 11

def pair( array, target ) :
    
    for i in array :
        addarray = array + i
        print(addarray)
        
pair( array, target )

[16 18 10 17 15 13]
[18 20 12 19 17 15]
[10 12  4 11  9  7]
[17 19 11 18 16 14]
[15 17  9 16 14 12]
[13 15  7 14 12 10]
